version: '2'
services:
  app:
    build: .
    command: bash -c "gem install bundler && bundle install --path='./.gems/' && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/CSV_Maker
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csv_development
      MYSQL_USER: csv2018
      MYSQL_PASSWORD: maker2018
    volumes:
      - ~/dockerdata/CSV_Maker/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --init-connect='SET NAMES UTF8;'
    ports:
      - "9090:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
